language: node_js

node_js:
  - node

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test

before_deploy:
  - yarn build

deploy:
  skip_cleanup: true
  provider: npm
  email: $EMAIL
  api_key:
    secure: $API_KEY
  on:
    tags: true
    repo: somadevs/neutron
