language: node_js

node_js:
  - node

cache:
  yarn: true
  directories:
    - node_modules

script:
  - bash scripts/travis-create-assets.sh
  - yarn lerna:format
  - yarn build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: website/build
    on:
      branch: master

  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    overwrite: true
    file: "temp/packages/*"
    on:
      tags: true
      repo: neutronjs/neutron

  - provider: script
    script: bash scripts/travis-deploy-npm.sh
    on:
      tags: true
      repo: neutronjs/neutron
