language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn format
deploy:
  provider: npm
  email: $EMAIL
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: neutronjs/neutron-cli
